### PR TITLE
Made a Calculator

### PR DESCRIPTION
**Pull request by gaut2003**
Made a calculator
Functionalities:
1) Buttons to add numbers.
2) Button to clear everything.
3) Button to compute the result.

### CODE REVIEW

**Comment by Axe-Pearl** [comment]
Thank you very much for your contribution

Let's Connect and learn together -
Instagram - https://www.instagram.com/anurag_nema_ytube/
You can find more issues here - > https://linktr.ee/anuragdev31

Also, Subscribe to our YouTube Channel where we talk about coding concepts, building amazing kinds of stuff, tips and tricks, and much more -
https://www.youtube.com/channel/UC8uVulieEYQWms4Jf8uxQ2g

**Comment by gaut2003** [comment]
Thank you
Looking forward to build connection to excel in open source.

**Comment by Axe-Pearl** [comment]
Hey @gaut2003, Please give star to this repository if this helped you

**Comment by gaut2003** [comment]
Why this repo is excluded from hacktoberfest 2022?

**Comment by Axe-Pearl** [comment]
@gaut2003, This Repository is under Hacktoberfest 2022, it takes time to update in the Hacktoberfest profile
Btw, if you still get any issues, you can inform me of the same.

**Comment by gaut2003** [comment]
Its showing that this repo is excluded from hacktoberfest 2022 in the official website.

**Comment by Axe-Pearl** [comment]
@gaut2003 , can you share screenshot please

**Comment by gaut2003** [comment]
Screenshot (158)

**Comment by Axe-Pearl** [comment]
@gaut2003, Fine I will check for the issue, do not worry. We will do something about it and inform you surely

**Comment by gaut2003** [comment]
OK @Axe-Pearl

**Comment by Axe-Pearl** [comment]
Hey @gaut2003, try to make a new pull request again. Maybe it will work now.
**Note - I have changed the name of Repo, keep your forked repository in sync with original repository**

**Pull request merged**
