### PR TITLE
TODO LIST 

### PR DESCRIPTION
**Pull request by Chaitanya-087**

### CODE REVIEW

**Comment by Axe-Pearl** [comment]
Thank you very much @Chaitanya-087

Let's Connect -
**Instagram** - https://www.instagram.com/anurag_nema_ytube/

**Subscribe to our YouTube Channel** where we talk about coding concepts, building amazing kinds of stuff, tips, and tricks, and much more -
https://www.youtube.com/channel/UC8uVulieEYQWms4Jf8uxQ2g

**Your Subscription will be highly appreciated**

**Comment by Chaitanya-087** [comment]
hi you forgot add tags please add them

**Comment by Axe-Pearl** [comment]
Hey @Chaitanya-087, check I had added labels in the issue section -
 https://github.com/Axe-Pearl/HacktoberfestRepo/issues/1#issuecomment-1269484785

This is pull request section, btw I added labels here too.

**Comment by Axe-Pearl** [comment]
Hey @Chaitanya-087 , I have added labels in Repository as well as here too

**Pull request merged**
